### ISSUE TITLE
Plz Help.

### ISSUE THREAD

**Issue by ejrhe** [demining/CryptoDeepTools#26]
Traceback (most recent call last):                      File "breakECDSA.py", line 11, in <module>              e = txnUtils.getSignableTxn(m)                      File "/data/data/com.termux/files/home/CryptoDeepTools/14FreyRuckAttack/txnUtils.py", line 53, in getSignableTxn                                                    inputAddr = base58.b58decode_check(keyUtils.pubKeyToAddr(pub))                                            File "/data/data/com.termux/files/home/CryptoDeepTools/14FreyRuckAttack/keyUtils.py", line 54, in pubKeyToAddr                                                      ripemd160 = hashlib.new('ripemd160')                File "/data/data/com.termux/files/usr/lib/python2.7/hashlib.py", line 116, in __py_new                        return __get_builtin_constructor(name)(string)      File "/data/data/com.termux/files/usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor        raise ValueError('unsupported hash type ' + name) ValueError: unsupported hash type ripemd160

This error occurs when i am tying to run python2 breakECDSA.py <BTC_RawTx_Hex>

How to fix it?

**Comment by demining** [comment]
@ejrhe https://github.com/demining/CryptoDeepTools/issues/19#issuecomment-1858305416

**Comment by ejrhe** [comment]
Sir can you plz provide me hashlib.py (that old version which is support on python2) so i can replace the existing on from /usr/lib/python2.7?
