### ISSUE TITLE
breakECDSA Error

### ISSUE THREAD

**Issue by Frogleim** [demining/CryptoDeepTools#27]
I got this error when trying to run `python2 breakECDSA.py 0100000001cb9a792b88760ad20c67047c06d016ba4a069d036c4fbc5c09a8055fe786580f300000006a4730440220331353fedfd6e4d6805fc1f06443ade552a43a43237fb6c3de3c7f0969b4cc6702200bfec7e7d2ae249b3d69cd8d666b5ee833394af3b0703fa023579200d9ab2ff401210335a395eca8191c43ccee4d91e98b9baef39476d7482cf636e5b71975c69feebdffffffff013a020000000000001976a914e94a23147d57674a7b817197be14877853590e6e88ac00000000
`

```
Traceback (most recent call last):
  File "breakECDSA.py", line 11, in <module>
    e = txnUtils.getSignableTxn(m)
  File "/home/frogleim/btc/CryptoDeepTools/15RowhammerAttack/txnUtils.py", line 53, in getSignableTxn
    inputAddr = base58.b58decode_check(keyUtils.pubKeyToAddr(pub))
  File "/home/frogleim/btc/CryptoDeepTools/15RowhammerAttack/keyUtils.py", line 54, in pubKeyToAddr
    ripemd160 = hashlib.new('ripemd160')
  File "/usr/lib/python2.7/hashlib.py", line 116, in __py_new
    return __get_builtin_constructor(name)(string)
  File "/usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type ripemd160
```

**Comment by demining** [comment]
**https://github.com/demining/CryptoDeepTools/issues/19**

**Comment by Zohaib121455** [comment]
breakecdsa  not working

**Comment by pkt-service** [comment]
I'm experiencing the same issue and am currently debugging it.

**Comment by PeterZSwallow** [comment]
Index 0
R = 331353fedfd6e4d6805fc1f06443ade552a43a43237fb6c3de3c7f0969b4cc67
S = 0bfec7e7d2ae249b3d69cd8d666b5ee833394af3b0703fa023579200d9ab2ff4
Z = 386ab315ab400d1421ebc87052e58e3bbb558bf04934751b4a8997c7f76dc245
PublicKey = 0335a395eca8191c43ccee4d91e98b9baef39476d7482cf636e5b71975c69feebd
